# Generated by Django 4.0.5 on 2022-07-04 12:59

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Kategorija')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(help_text='Įveskite tiekejo pavadinimą', max_length=200, verbose_name='Tiekėjas')),
                ('email', models.EmailField(default=orders.models.default_mail, help_text='Iveskite tiekejo elektronini pasta', max_length=50, verbose_name='Elektroninis pastas')),
                ('phone', models.CharField(default=orders.models.default_number, help_text='Iveskite tiekejo Telefono numeri', max_length=50, verbose_name='Telefono numeris')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=50, verbose_name='Uzsakymas')),
                ('amount', models.FloatField(max_length=5, verbose_name='Kiekis')),
                ('unit', models.CharField(blank=True, choices=[('a', 'Vnt'), ('b', 'Kg'), ('c', 'G'), ('d', 'L')], default='a', max_length=1, verbose_name='Mato Vienetas')),
                ('order_code', models.CharField(blank=True, max_length=20, verbose_name='Kodas')),
                ('note', models.CharField(blank=True, max_length=50, verbose_name='Aprasymas')),
                ('category', models.ManyToManyField(help_text='Priskirkite kategorijai', to='orders.categories')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.supplier')),
            ],
        ),
    ]
